"""empty message

Revision ID: 04b524913e9e
Revises: 7719833495df
Create Date: 2020-12-10 20:01:39.221367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b524913e9e'
down_revision = '7719833495df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commerces', sa.Column('avatar', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commerces', 'avatar')
    # ### end Alembic commands ###
