"""empty message

Revision ID: 1da59c296387
Revises: 46f8dbcb7ddc
Create Date: 2020-12-07 18:52:28.658506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da59c296387'
down_revision = '46f8dbcb7ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('commerces', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'commerces', 'users', ['owner_id'], ['id'])
    op.add_column('followers', sa.Column('commerce_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'followers', 'commerces', ['commerce_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_column('followers', 'commerce_id')
    op.drop_constraint(None, 'commerces', type_='foreignkey')
    op.drop_column('commerces', 'owner_id')
    op.drop_table('likes')
    # ### end Alembic commands ###
