"""empty message

Revision ID: 29b01226b6f6
Revises: ac3bef9d5906
Create Date: 2021-01-19 15:09:44.412194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b01226b6f6'
down_revision = 'ac3bef9d5906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('promo_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'promo_code')
    # ### end Alembic commands ###
