"""empty message

Revision ID: 6765c82ecc07
Revises: c3e1cb69b0b3
Create Date: 2020-12-13 22:47:15.108673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6765c82ecc07'
down_revision = 'c3e1cb69b0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_response_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('commerce_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'commerces', ['commerce_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'comments', ['comment_response_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'commerce_id')
    op.drop_column('comments', 'comment_response_id')
    # ### end Alembic commands ###
