"""empty message

Revision ID: a91709980464
Revises: a5b6f858a3db
Create Date: 2021-01-04 11:43:18.280102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91709980464'
down_revision = 'a5b6f858a3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('is_active', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('is_active', 'users', ['is_active'], unique=True)
    # ### end Alembic commands ###
