"""empty message

Revision ID: b05557aa9ffa
Revises: da5d97f62ded
Create Date: 2020-12-14 19:46:42.534269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b05557aa9ffa'
down_revision = 'da5d97f62ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.drop_constraint('comments_ibfk_1', 'comments', type_='foreignkey')
    op.drop_column('comments', 'commerce_id')
    op.drop_column('comments', 'comment_response_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_response_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('commerce_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_ibfk_1', 'comments', 'comments', ['comment_response_id'], ['id'])
    op.create_foreign_key('comments_ibfk_2', 'comments', 'commerces', ['commerce_id'], ['id'])
    # ### end Alembic commands ###
