"""empty message

Revision ID: c05c5f00fac1
Revises: eabaaf9d9650
Create Date: 2020-12-07 20:02:08.134773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05c5f00fac1'
down_revision = 'eabaaf9d9650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
