"""empty message

Revision ID: eabaaf9d9650
Revises: 1da59c296387
Create Date: 2020-12-07 19:56:07.154264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabaaf9d9650'
down_revision = '1da59c296387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('comments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.add_column('commerces', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('commerces', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('commerces', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('followers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('followers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('followers', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('followers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'followers', 'users', ['user_id'], ['id'])
    op.add_column('likes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('likes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('likes', sa.Column('post_id', sa.Integer(), nullable=False))
    op.add_column('likes', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'])
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'created_at')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'deleted_at')
    op.drop_column('posts', 'created_at')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'updated_at')
    op.drop_column('likes', 'post_id')
    op.drop_column('likes', 'deleted_at')
    op.drop_column('likes', 'created_at')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_column('followers', 'user_id')
    op.drop_column('followers', 'updated_at')
    op.drop_column('followers', 'deleted_at')
    op.drop_column('followers', 'created_at')
    op.drop_column('commerces', 'updated_at')
    op.drop_column('commerces', 'deleted_at')
    op.drop_column('commerces', 'created_at')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'post_id')
    op.drop_column('comments', 'deleted_at')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
